// muiTheme.js
import { createTheme } from "@mui/material/styles";
import { theme as customTheme } from "./theme";

export const muiTheme = createTheme({
  palette: {
    primary: { main: customTheme.colors.primary },
    secondary: { main: customTheme.colors.secondary },
    error: { main: customTheme.colors.error },
    info: { main: customTheme.colors.info },
    success: { main: customTheme.colors.success },
    warning: { main: customTheme.colors.warning },
    background: {
      default: customTheme.colors.background,
      paper: customTheme.colors.white,
      background_Dark: customTheme.colors.background_Dark,
    },
    text: {
      primary: customTheme.colors.black,
      secondary: customTheme.colors.secondary,
    },
    purple: {
      purple: customTheme.colors.purple.purple,
      lighten_1: customTheme.colors.purple.lighten_1,
      lighten_2: customTheme.colors.purple.lighten_2,
      lighten_3: customTheme.colors.purple.lighten_3,
      lighten_4: customTheme.colors.purple.lighten_4,
      lighten_5: customTheme.colors.purple.lighten_5,
      darken_1: customTheme.colors.purple.darken_1,
      darken_2: customTheme.colors.purple.darken_2,
      darken_3: customTheme.colors.purple.darken_3,
      darken_4: customTheme.colors.purple.darken_4,
      accent_1: customTheme.colors.purple.accent_1,
      accent_2: customTheme.colors.purple.accent_2,
      accent_3: customTheme.colors.purple.accent_3,
      accent_4: customTheme.colors.purple.accent_4,
    },
    grey: {
      grey: customTheme.colors.grey.grey,
      lighten_1: customTheme.colors.grey.lighten_1,
      lighten_2: customTheme.colors.grey.lighten_2,
      lighten_3: customTheme.colors.grey.lighten_3,
      lighten_4: customTheme.colors.grey.lighten_4,
      lighten_5: customTheme.colors.grey.lighten_5,
      darken_1: customTheme.colors.grey.darken_1,
      darken_2: customTheme.colors.grey.darken_2,
      darken_3: customTheme.colors.grey.darken_3,
      darken_4: customTheme.colors.grey.darken_4,
    },
    green: {
      green: customTheme.colors.green.green,
      lighten_1: customTheme.colors.green.lighten_1,
      lighten_2: customTheme.colors.green.lighten_2,
      lighten_3: customTheme.colors.green.lighten_3,
      lighten_4: customTheme.colors.green.lighten_4,
      lighten_5: customTheme.colors.green.lighten_5,
      darken_1: customTheme.colors.green.darken_1,
      darken_2: customTheme.colors.green.darken_2,
      darken_3: customTheme.colors.green.darken_3,
      darken_4: customTheme.colors.green.darken_4,
      accent_1: customTheme.colors.green.accent_1,
      accent_2: customTheme.colors.green.accent_2,
      accent_3: customTheme.colors.green.accent_3,
      accent_4: customTheme.colors.green.accent_4,
    },
  },
  typography: {
    fontFamily: customTheme.fonts.main,
    h1: {
      fontFamily: customTheme.fonts.heading,
      fontSize: customTheme.fontSizes["5xl"],
    },
    h2: {
      fontFamily: customTheme.fonts.heading,
      fontSize: customTheme.fontSizes["4xl"],
    },
    body1: { fontSize: customTheme.fontSizes.md },
    body2: { fontSize: customTheme.fontSizes.sm },
  },
});
